name: hello_world_mvp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  build_runner: ^2.4.12
  dio: ^5.6.0
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.2
  go_router: ^14.2.7
  http: ^1.2.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  package_info_plus: ^8.0.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  universal_html: ^2.2.4
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.2
  google_sign_in: ^6.2.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  injectable: ^2.4.4
  uuid: ^4.5.0
  version: ^3.0.2
  get_it: ^7.6.6
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  injectable_generator:

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/images/auth/
    - assets/fonts/
