name: hello_world_mvp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.2
  go_router: ^14.2.7
  http: ^1.2.2
  package_info_plus: ^8.0.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/fonts/
