name: hello_world_mvp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.2

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  build_runner: ^2.4.12
  dio: ^5.6.0
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.2
  go_router: ^14.2.7
  http: ^1.2.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  package_info_plus: ^8.0.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  universal_html: ^2.2.4
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.2
  google_sign_in: ^6.2.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  injectable: ^2.4.4
  uuid: ^4.5.0
  version: ^3.0.2
  get_it: ^7.6.6
  hive: ^2.2.3
  flutter_bloc: ^8.1.6
  rxdart: ^0.28.0
  flutter_svg: ^2.0.10+1
  country_icons: ^3.0.0
  image_picker: ^1.1.2
  sentry_flutter: ^8.10.1
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.2
  google_maps_flutter_platform_interface: ^2.9.5
  google_maps_flutter_android: ^2.14.11
  synchronized: ^3.3.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  injectable_generator:

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/images/auth/
    - assets/images/home/
    - assets/images/home/grid_view/
    - assets/images/chat/
    - assets/images/common/
    - assets/images/mypage/
    - assets/fonts/
    - assets/icons/
    - assets/icons/grey/
    - assets/icons/blue/
    - assets/images/common/flags/

  fonts:
    - family: SB AggroOTF
      fonts:
        - asset: assets/fonts/SB-AggroOTF-Bold.otf
          weight: 700
        - asset: assets/fonts/SB-AggroOTF-Medium.otf
          weight: 500
        - asset: assets/fonts/SB-AggroOTF-Light.otf
          weight: 300

    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Black.otf
          weight: 900
        - asset: assets/fonts/pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/pretendard/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/pretendard/Pretendard-Thin.otf
          weight: 100
